---
title: "Data_Tidying"
author: "Miles Spathelf"
date: "May 17, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_libraries, message=FALSE, warning=FALSE}
library(dplyr)
library(tidyr)
```

Reads in the data from KNB 

```{r}
catch_df <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1", method = "libcurl"),
                    stringsAsFactors = FALSE)
head(catch_df)
```

Select the columns we want, changes to tall format, and renames catch column

```{r}
catch_df<- catch_df %>% 
  select(Region, Year, Chinook, Sockeye, Coho, Pink, Chum) %>% 
  gather(key = species, value = catch, -Region, -Year) %>% 
  rename(catch_thousands = catch)

```

Correct type and change units of catch column

```{r}
catch_df <- catch_df %>% 
  mutate(catch_thousands = ifelse(catch_thousands == "I", 1, catch_thousands)) %>% 
  mutate(catch_thousands = as.integer(catch_thousands)) %>% 
  mutate(catch = catch_thousands * 1000)
 
```
  

#Analysis

```{r}
catch_df %>% 
    filter(species == Chinook)

```

Calculate chinook catch by region and year

```{r}
annual_catch <- catch_df %>% 
  filter(species == "Chinook") %>% 
  group_by(Region, Year) %>% 
  summarise(mean_catch = mean(catch), num_obs=n()) %>% 
  arrange(desc(mean_catch))

head(annual_catch, 30)
```


Read in Regions definitions table and select code and management area columns

```{r}
region_defs <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.303.1", method = "libcurl"),
                        stringsAsFactors = FALSE) %>% 

  select(code, mgmtArea)
```

```{r}

catch_joined <- left_join(catch_df, region_defs, by = c("Region" = "code"))

head(catch_joined)

```



